const user = [
  { name: 'Alisa Wang', url: 'Alisa_Wang' },
  { name: 'Angela Long', url: 'Angela_Long' },
  { name: 'Angela Kong', url: 'Angela_Kong' },
  { name: 'Annie Tang', url: 'Annie_Tang' },
  { name: 'Anqi Hu', url: 'Anqi_Hu' },
  { name: 'Ariel Chen', url: 'Ariel_Chen' },
  { name: 'Audrey Guo', url: 'Audrey_Guo' },
  { name: 'Bill Wang', url: 'Bill_Wang' },
  { name: 'Billy Sun', url: 'Billy_Sun' },
  { name: 'Brenda Zhao', url: 'Brenda_Zhao' },
  { name: 'Carmen Jiang', url: 'Carmen_Jiang' },
  { name: 'Catherine Kong', url: 'Catherine_Kong' },
  { name: 'Cecilia Zhang', url: 'Cecilia_Zhang' },
  { name: 'Chloe Jin', url: 'Chloe_Jin' },
  { name: 'Chris Xu', url: 'Chris_Xu' },
  { name: 'Daniel Zhou', url: 'Daniel_Zhou' },
  { name: 'Do_Young Jeong', url: 'Do_Young_Jeong' },
  { name: 'Elaine Shen', url: 'Elaine_Shen' },
  { name: 'Emily Hua', url: 'Emily_Hua' },
  { name: 'Erik Emilsson', url: 'Erik_Emilsson' },
  { name: 'Gina Tang', url: 'Gina_Tang' },
  { name: 'Irwin Wen', url: 'Irwin_Wen' },
  { name: 'Jeff Zheng', url: 'Jeff Zheng' },
  { name: 'Jeff Chen', url: 'Jeff_Chen' },
  { name: 'Jenny Yan', url: 'Jenny_Yan' },
  { name: 'Jiahui Hou', url: 'Jiahui_Hou' },
  { name: 'Joanne Goh', url: 'Joanne_Goh' },
  { name: 'Johnson Cui', url: 'Johnson_Cui' },
  { name: 'Jolin Shi', url: 'Jolin_Shi' },
  { name: 'Judy Liu', url: 'Judy_Liu' },
  { name: 'Kelly He', url: 'Kelly_He' },
  { name: 'Lancy Wang', url: 'Lancy_Wang' },
  { name: 'Lei Wang', url: 'Lei_Wang' },
  { name: 'Lilian Xu', url: 'Lilian_Xu' },
  { name: 'Lina Tao', url: 'Lina_Tao' },
  { name: 'Lu Shi', url: 'Lu_Shi' },
  { name: 'Luna Chen', url: 'Luna_Chen' },
  { name: 'Michael Chung', url: 'Michael_Chung' },
  { name: 'Michael Zhu', url: 'Michael_Zhu' },
  { name: 'Nichole Kuang', url: 'Nichole_Kuang' },
  { name: 'Oskar Gu', url: 'Oskar_Gu' },
  { name: 'Rachel Han', url: 'Rachel_Han' },
  { name: 'Roderick Peek', url: 'Roderick_Peek' },
  { name: 'Shawn Shao', url: 'Shawn_Shao' },
  { name: 'Sylvia Wang', url: 'Sylvia_Wang' },
  { name: 'Yufei Mao', url: 'Yufei_Mao' },
  { name: 'Zoe Zhang', url: 'Zoe_Zhang' },
]

export default user