const user = [
  { name: 'Ailsa_Wang_GSG', url: 'Ailsa_Wang_GSG' },
  { name: 'Angel Guo_TTLC', url: 'Angel Guo_TTLC' },
  { name: 'Angel_Ding_GSG', url: 'Angel_Ding_GSG' },
  { name: 'Annie_Tang_GSG', url: 'Annie_Tang_GSG' },
  { name: 'Ariel_Chen_GSG', url: 'Ariel_Chen_GSG' },
  { name: 'Audrey_Guo_GSG', url: 'Audrey_Guo_GSG' },
  { name: 'Belle_Xia_TTLC', url: 'Belle_Xia_TTLC' },
  { name: 'Bill_Wang_GSG', url: 'Bill_Wang_GSG' },
  { name: 'Cathy_Zheng_TTLC', url: 'Cathy_Zheng_TTLC' },
  { name: 'Chloe_Jin_GSG', url: 'Chloe_Jin_GSG' },
  { name: 'Daniel_Zhou_Pool_RA', url: 'Daniel_Zhou_Pool_RA' },
  { name: 'Emma_Lin_GSG', url: 'Emma_Lin_GSG' },
  { name: 'Hao_Wang_TTLC', url: 'Hao_Wang_TTLC' },
  { name: 'Helen_Zhang_GSG', url: 'Helen_Zhang_GSG' },
  { name: 'Irwin_Weng_Pool_RA', url: 'Irwin_Weng_Pool_RA' },
  { name: 'Jane_Ge_TTLC', url: 'Jane_Ge_TTLC' },
  { name: 'Jerri_Xu_GSG', url: 'Jerri_Xu_GSG' },
  { name: 'Jesse_Song_TTLC', url: 'Jesse_Song_TTLC' },
  { name: 'Jessica_He_GSG', url: 'Jessica_He_GSG' },
  { name: 'Johnson_Cui_GSG', url: 'Johnson_Cui_GSG' },
  { name: 'Jolin_Shi_GSG', url: 'Jolin_Shi_GSG' },
  { name: 'Kelly_He_GSG', url: 'Kelly_He_GSG' },
  { name: 'Kitty_Chen_GSG', url: 'Kitty_Chen_GSG' },
  { name: 'Lei_Wang_GSG', url: 'Lei_Wang_GSG' },
  { name: 'Lin_Qi_GSG', url: 'Lin_Qi_GSG' },
  { name: 'Lina_Tao_GSG', url: 'Lina_Tao_GSG' },
  { name: 'Lizi_Chen_GSG', url: 'Lizi_Chen_GSG' },
  { name: 'Luna_Chen_GSG', url: 'Luna_Chen_GSG' },
  { name: 'Manni_Xu_GSG', url: 'Manni_Xu_GSG' },
  { name: 'Mary_Ma_GSG', url: 'Mary_Ma_GSG' },
  { name: 'Naitong_Ji_TTLC', url: 'Naitong_Ji_TTLC' },
  { name: 'Silver_Xie_GSG', url: 'Silver_Xie_GSG' },
  { name: 'Sunny_Chen_TTLC', url: 'Sunny_Chen_TTLC' },
  { name: 'Tina_Song_TTLC', url: 'Tina_Song_TTLC' },
  { name: 'Ting_Ou_TTLC', url: 'Ting_Ou_TTLC' },
  { name: 'Vera_Zeng_GSG', url: 'Vera_Zeng_GSG' },
  { name: 'Wendy_Wang_GSG', url: 'Wendy_Wang_GSG' },
  { name: 'Xinxin_Wang_Pool RA', url: 'Xinxin_Wang_Pool RA' },
  { name: 'Yaning_Zhang_TTLC', url: 'Yaning_Zhang_TTLC' },
  { name: 'Yuting_Zhu_TTLC', url: 'Yuting_Zhu_TTLC' },
]

export default user