const user = [
  // { name: 'Alisa Wang', url: 'Alisa_Wang' },
  // { name: 'Angela Long', url: 'Angela_Long' },
  // { name: 'Angela Kong', url: 'Angela_Kong' },
  // { name: 'Annie Tang', url: 'Annie_Tang' },
  // { name: 'Anqi Hu', url: 'Anqi_Hu' },
  // { name: 'Ariel Chen', url: 'Ariel_Chen' },
  // { name: 'Audrey Guo', url: 'Audrey_Guo' },
  // { name: 'Bill Wang', url: 'Bill_Wang' },
  // { name: 'Billy Sun', url: 'Billy_Sun' },
  // { name: 'Brenda Zhao', url: 'Brenda_Zhao' },
  // { name: 'Carmen Jiang', url: 'Carmen_Jiang' },
  // { name: 'Catherine Kong', url: 'Catherine_Kong' },
  // { name: 'Cecilia Zhang', url: 'Cecilia_Zhang' },
  // { name: 'Chloe Jin', url: 'Chloe_Jin' },
  // { name: 'Chris Xu', url: 'Chris_Xu' },
  // { name: 'Daniel Zhou', url: 'Daniel_Zhou' },
  // { name: 'Do_Young Jeong', url: 'Do_Young_Jeong' },
  // { name: 'Elaine Shen', url: 'Elaine_Shen' },
  // { name: 'Emily Hua', url: 'Emily_Hua' },
  // { name: 'Erik Emilsson', url: 'Erik_Emilsson' },
  // { name: 'Gina Tang', url: 'Gina_Tang' },
  // { name: 'Irwin Wen', url: 'Irwin_Wen' },
  // { name: 'Jeff Zheng', url: 'Jeff Zheng' },
  // { name: 'Jeff Chen', url: 'Jeff_Chen' },
  // { name: 'Jenny Yan', url: 'Jenny_Yan' },
  // { name: 'Jiahui Hou', url: 'Jiahui_Hou' },
  // { name: 'Joanne Goh', url: 'Joanne_Goh' },
  // { name: 'Johnson Cui', url: 'Johnson_Cui' },
  // { name: 'Jolin Shi', url: 'Jolin_Shi' },
  // { name: 'Judy Liu', url: 'Judy_Liu' },
  // { name: 'Kelly He', url: 'Kelly_He' },
  // { name: 'Lancy Wang', url: 'Lancy_Wang' },
  // { name: 'Lei Wang', url: 'Lei_Wang' },
  // { name: 'Lilian Xu', url: 'Lilian_Xu' },
  // { name: 'Lina Tao', url: 'Lina_Tao' },
  // { name: 'Lu Shi', url: 'Lu_Shi' },
  // { name: 'Luna Chen', url: 'Luna_Chen' },
  // { name: 'Michael Chung', url: 'Michael_Chung' },
  // { name: 'Michael Zhu', url: 'Michael_Zhu' },
  // { name: 'Nichole Kuang', url: 'Nichole_Kuang' },
  // { name: 'Oskar Gu', url: 'Oskar_Gu' },
  // { name: 'Rachel Han', url: 'Rachel_Han' },
  // { name: 'Roderick Peek', url: 'Roderick_Peek' },
  // { name: 'Shawn Shao', url: 'Shawn_Shao' },
  // { name: 'Sylvia Wang', url: 'Sylvia_Wang' },
  // { name: 'Yufei Mao', url: 'Yufei_Mao' },
  // { name: 'Zoe Zhang', url: 'Zoe_Zhang' },

  { name: 'Ailsa_Wang_GSG', url: 'Ailsa_Wang_GSG' },
  { name: 'Angel Guo_TTLC', url: 'Angel Guo_TTLC' },
  { name: 'Angel_Ding_GSG', url: 'Angel_Ding_GSG' },
  { name: 'Annie_Tang_GSG', url: 'Annie_Tang_GSG' },
  { name: 'Ariel_Chen_GSG', url: 'Ariel_Chen_GSG' },
  { name: 'Audrey_Guo_GSG', url: 'Audrey_Guo_GSG' },
  { name: 'Belle_Xia_TTLC', url: 'Belle_Xia_TTLC' },
  { name: 'Bill_Wang_GSG', url: 'Bill_Wang_GSG' },
  { name: 'Cathy_Zheng_TTLC', url: 'Cathy_Zheng_TTLC' },
  { name: 'Chloe_Jin_GSG', url: 'Chloe_Jin_GSG' },
  { name: 'Daniel_Zhou_Pool RA', url: 'Daniel_Zhou_Pool RA' },
  { name: 'Emma_Lin_GSG', url: 'Emma_Lin_GSG' },
  { name: 'Hao_Wang_TTLC', url: 'Hao_Wang_TTLC' },
  { name: 'Helen_Zhang_GSG', url: 'Helen_Zhang_GSG' },
  { name: 'Irwin_Weng_Pool RA', url: 'Irwin_Weng_Pool RA' },
  { name: 'Jane_Ge_TTLC', url: 'Jane_Ge_TTLC' },
  { name: 'Jerri_Xu_GSG', url: 'Jerri_Xu_GSG' },
  { name: 'Jesse_Song_TTLC', url: 'Jesse_Song_TTLC' },
  { name: 'Jessica_He_GSG', url: 'Jessica_He_GSG' },
  { name: 'Johnson_Cui_GSG', url: 'Johnson_Cui_GSG' },
  { name: 'Jolin_Shi_GSG', url: 'Jolin_Shi_GSG' },
  { name: 'Kelly_He_GSG', url: 'Kelly_He_GSG' },
  { name: 'Kitty_Chen_GSG', url: 'Kitty_Chen_GSG' },
  { name: 'Lei_Wang_GSG', url: 'Lei_Wang_GSG' },
  { name: 'Lina_Tao_GSG', url: 'Lina_Tao_GSG' },
  { name: 'Lin_Qi_GSG', url: 'Lin_Qi_GSG' },
  { name: 'LIST.TXT', url: 'LIST.TXT' },
  { name: 'Lizi_Chen_GSG', url: 'Lizi_Chen_GSG' },
  { name: 'Luna_Chen_GSG', url: 'Luna_Chen_GSG' },
  { name: 'Manni_Xu_GSG', url: 'Manni_Xu_GSG' },
  { name: 'Mary_Ma_GSG', url: 'Mary_Ma_GSG' },
  { name: 'Naitong_Ji_TTLC', url: 'Naitong_Ji_TTLC' },
  { name: 'Silver_Xie_GSG', url: 'Silver_Xie_GSG' },
  { name: 'Sunny_Chen_TTLC', url: 'Sunny_Chen_TTLC' },
  { name: 'Tina_Song_TTLC', url: 'Tina_Song_TTLC' },
  { name: 'Ting_Ou_TTLC.PNG', url: 'Ting_Ou_TTLC.PNG' },
  { name: 'Vera_Zeng_GSG', url: 'Vera_Zeng_GSG' },
  { name: 'Wendy_Wang_GSG', url: 'Wendy_Wang_GSG' },
  { name: 'Xinxin_Wang_Pool RA', url: 'Xinxin_Wang_Pool RA' },
  { name: 'Yaning_Zhang_TTLC', url: 'Yaning_Zhang_TTLC' },
  { name: 'Yuting_Zhu_TTLC', url: 'Yuting_Zhu_TTLC' },


]

export default user